project_id = "lvvvjywrmpcqrpvuptdi"

[db]
shadow_port = 54332

[functions.sync-campaign-to-edusite]
verify_jwt = false

[functions.sync-registrations-from-edusite]
verify_jwt = false

[functions.notifications-dispatcher]
verify_jwt = false

[functions.daily-token]
verify_jwt = true

[functions.daily-rooms]
verify_jwt = true

[functions.superadmin-delete-user]
verify_jwt = true
